### ISSUE TITLE
Vanishing header in two-header table

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#1]
There is a bug in Tab. 4.3 (https://nrpmhandbook.reliability.space/_static/interactivity/html/syst_table4_3.html):
Entering and deleting a search term removes the second header from the table.

**Comment by csxADS** [comment]
Done

**Comment by paulremo** [comment]
This issue still persists in the live version - did you make changes to the interactivity repository that you did not push?

**Comment by paulremo** [comment]
My bad  - it works now!
