### ISSUE TITLE
Acronyms in file names

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#12]
We should not use acronyms in file names, with the exception of EEE. Therefore, *rp* should be replaced by *reliability_prediction* in all folders and files.

**Comment by csxADS** [comment]
Solved in commit "changed acronyms for rp"

**Comment by paulremo** [comment]
You missed a file (\mechanical\handbook\reliability_prediction\process_rp.md)

**Comment by csxADS** [comment]
Done commit eca78560243d3abcfeaeba8412c9204c6d186e0f

**Comment by paulremo** [comment]
Thanks!
