### ISSUE TITLE
Redirect javascript hides broken links

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#48]
To allow an automatic link checker to detect broken links, the redirect function in `redirect.js` should no longer be used. I found two different use cases for this function that will have to be changed:

- [x] **image links**: 
change 
`<img class="link-image" src="_static/images/methodPicture.png" alt="logo methods" onclick="redirect('methods/handbook/intro.html')">` 
to
`<a href="methods/handbook/intro.html"><img class="link-image" src="_static/images/methodPicture.png" alt="logo methods"></a>`
- [x] **back-forward button**:
change 
`<button id="solid_lubricant_button" class="back-forward-button" onclick="redirect('../../models/solid_lubricant_wear.html')">Go to model</button>`
to
`<a href="../../models/solid_lubricant_wear.html" class="back-forward-button">Go to model</a>`

Note: For the `back-forward-button` style you will have to make some modifications to make the link look like a button. Have a look at [this page](https://www.w3docs.com/snippets/html/how-to-create-an-html-button-that-acts-like-a-link.html).

Do you think this is feasible, or am I missing something?

**Comment by csxADS** [comment]
fixed, did my best for the CSS but it's less pretty

**Comment by paulremo** [comment]
Thanks! I found two issues:

- [ ] I think you missed some back-forward buttons (search for `<button`, I still found two)
- [ ] The CSS doesn't work on my side (padding of the button is not visible). Is it because you define the `.back-forward-button` style twice inside `mybutton.css`?

**Comment by paulremo** [comment]
Two more small things concerning the `.back-forward-button` CSS style, than you can close this issue:

- [ ] I think you have to use the `!important` flag in the color property to not have the color be overwritten with the default link color. Do you think there is a more elegant solution?
- [ ]  reduce the vertical padding (first argument of the `.padding` property to get a more elongated, less bulky button (e.g. 5px)
